server:
  http_listen_port: 3100

positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot-app
          __path__: /var/log/app-logs/*.log